[general]
target_path=/var/www/html
debug=false
threads=0
list=txt js css svg json html htm map
algorithms=all
gzip_level=9
brotli_level=11
optimal_min_compress_size=1024
debounce_delay=2
io_delay_us=0
max_active_ios=0
process_files_without_extensions=false
enable_folder_overrides=true
drop_privileges=true
enable_seccomp=true
run_as_user=

# mh-compressor-manager: MERGE_BOUNDARY (не удалять)
